require("nikola/keybindings")
require("nikola/options")
require("nikola/plugins")
require("nikola/colorscheme")
require("nikola/cmp")
require("nikola/lsp/init")
require("nikola/telescope")
require("nikola/treesitter")
require("nikola/autopairs")
require("nikola/comments")
require("nikola/gitsigns")
require("nikola/nvim-tree")
require("nikola/bufferline")
require("nikola/lualine")
require("nikola/colorizer")
require("nikola/project")
require("nikola/indentline")
require("nikola/impatient")
require("nikola/coc")
--[[ require("nikola/illuminate") ]]
--[[ vim.cmd([[autocmd BufNewFile,BufRead *.log set filetype=log]]
--)
