vim.cmd "autocmd ColorScheme * highlight Normal     ctermbg=NONE guibg=NONE"
vim.cmd "autocmd ColorScheme * highlight SignColumn ctermbg=NONE guibg=NONE"
vim.cmd "autocmd ColorScheme * highlight Todo   ctermbg=NONE guibg=NONE"
vim.cmd "colorscheme darkplus"
vim.cmd "set termguicolors"
vim.cmd "set background=dark"
