vim.cmd "colorscheme gruvbox-material"
vim.cmd "set termguicolors"
vim.cmd "autocmd colorscheme * highlight normal     ctermbg=none guibg=none"
vim.cmd "autocmd colorscheme * highlight signcolumn ctermbg=none guibg=none"
vim.cmd "autocmd colorscheme * highlight todo   ctermbg=none guibg=none"
